# Generated by Django 3.1 on 2023-01-17 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=255, verbose_name='Наименование компании')),
                ('slug', models.SlugField(unique=True)),
                ('scheduleStart', models.TimeField(verbose_name='Начало работы')),
                ('scheduleFinish', models.TimeField(verbose_name='Конец работы')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram аккаунт')),
                ('yandexMapLink', models.CharField(max_length=500, verbose_name='Ссылка на карту')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.category', verbose_name='Категория')),
                ('masters', models.ManyToManyField(to='coreApp.Master')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=models.Model, to='coreApp.rating', verbose_name='Рейтинг')),
                ('services', models.ManyToManyField(to='coreApp.Service')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
