# Generated by Django 3.1 on 2023-01-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255, verbose_name='Наименование категории'), unique=True, verbose_name='Ссылка категории'),
        ),
    ]
