# Generated by Django 3.1 on 2023-02-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0007_auto_20230117_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О проекте',
                'verbose_name_plural': 'О проекте',
            },
        ),
    ]
