# Generated by Django 3.1 on 2023-02-01 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0008_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 11, 56, 16, 814086), verbose_name='Дата публикации'),
        ),
    ]
