# Generated by Django 3.1 on 2023-02-02 12:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreApp', '0009_business_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 18, 48, 32, 721481), verbose_name='Дата публикации'),
        ),
        migrations.CreateModel(
            name='QueryTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=255, verbose_name='Компания')),
                ('service', models.CharField(max_length=255, verbose_name='Услуга')),
                ('master', models.CharField(max_length=255, verbose_name='Мастер')),
                ('recordDate', models.DateTimeField(verbose_name='Дата и время записи')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('userQuery', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тест',
            },
        ),
    ]
