# Generated by Django 3.1 on 2023-02-02 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0010_auto_20230202_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querytest',
            old_name='userQuery',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='business',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 22, 28, 33, 783927), verbose_name='Дата публикации'),
        ),
    ]
