# Generated by Django 3.1 on 2023-02-02 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0011_auto_20230202_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='querytest',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='business',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 22, 33, 54, 807569), verbose_name='Дата публикации'),
        ),
    ]
