# Generated by Django 3.1 on 2023-02-02 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0013_auto_20230202_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 22, 46, 59, 645480), verbose_name='Дата публикации'),
        ),
    ]
