# Generated by Django 4.1.7 on 2023-02-20 12:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreApp', '0015_alter_aboutpage_id_alter_business_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время записи')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('isActive', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AlterField(
            model_name='business',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 18, 39, 0, 690097), verbose_name='Дата публикации'),
        ),
        migrations.DeleteModel(
            name='QueryTest',
        ),
        migrations.AddField(
            model_name='query',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.business', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
