# Generated by Django 4.1.7 on 2023-02-20 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0016_query_alter_business_postdate_delete_querytest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='master',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='coreApp.master', verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='query',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='coreApp.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='business',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 19, 7, 31, 604432), verbose_name='Дата публикации'),
        ),
    ]
