# Generated by Django 4.1.7 on 2023-03-15 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0017_query_master_query_service_alter_business_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='business/covers/', verbose_name='Изображение (500x500)'),
        ),
        migrations.AddField(
            model_name='category',
            name='fontAwesomeClass',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AlterField(
            model_name='business',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 19, 27, 5, 620119), verbose_name='Дата публикации'),
        ),
    ]
