# Generated by Django 4.1.7 on 2023-03-23 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0019_alter_business_postdate_userdataprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 14, 5, 14, 89631), verbose_name='Дата публикации'),
        ),
    ]
